make:
	rm simulation/*.class
	javac simulation/SimpleSimulation.java
	java simulation/SimpleSimulation

brown:
	rm simulation/*.class
	javac simulation/BrownianSimulation.java
	java simulation/BrownianSimulation

diffusion:
	rm simulation/*.class
	javac simulation/DiffusionSimulation.java
	java simulation/DiffusionSimulation


clean:
	rm simulation/*.class
