make:
	if [-a *.class];\
	then \
		rm simulation/*.class;\
	fi;
	javac simulation/SimpleSimulation.java
	java simulation/SimpleSimulation

brown:
	if [-a *.class];\
	then \
		rm simulation/*.class;\
	fi;
	javac simulation/BrownianSimulation.java
	java simulation/BrownianSimulation

diffusion:
	if [-a *.class];\
	then \
		rm simulation/*.class;\
	fi;
	javac simulation/DiffusionSimulation.java
	java simulation/DiffusionSimulation


clean:
	rm simulation/*.class
